config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profile', to: 'users#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  post "/payment", to: "payments#create"

  resources :messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  resources :users, only: %i[index]

  resources :posts, except: [:index] do 
    resources :comments, only: [:create]
  end

  resources :fav_posts do 
    collection do
      get :favourite
      get :unfavourite
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/conversation.rb
class Conversation < ApplicationRecord

    include Test

    belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'

    validates :sender, uniqueness: {scope: :receiver}
    has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy

    # scope :participating, -> user do
    #     where("(conversations.sender_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
    # end

    # scope :between, -> (sender_id, receiver_id) do
    #     where(sender_id: sender_id, receiver_id: receiver_id).or(where(sender_id: receiver_id, receiver_id: sender_id)).limit(1)
    # end

    # def with(current_user)
    #     sender == current_user ? receiver : sender
    # end

    # def participates?(user)
    #     sender == user || receiver == user
    # end
    

end 

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

    before_action :set_conversation, except: [:index]
    before_action :check_participating!, except: [:index]

    def index
        @conversations = Conversation.participating(current_user).order('updated_at DESC')
    end

    def show
        @message = Message.new
    end


    private 

    def set_conversation
        @conversation = Conversation.find_by(id: params[:id])
    end
    
    def check_participating!
        redirect_to root_path unless @conversation && @conversation.participates?(current_user)
    end


end

app/views/conversations/_conversations.html.erb
<div>
  Chatting with <%= conversation.with(current_user).username %>
  <br>
  <em><%= conversation.messages.last.body.truncate(50) %></em>
  <br>
  <%= link_to 'View conversation', conversation_path(conversation) %>
  <hr>
</div>

app/views/conversations/index.html.erb
<h1>Your conversations</h1>

<div id="conversations">
  <%= render @conversations %>
</div>

app/views/conversations/show.html.erb
<h1>Chatting with <%= @conversation.with(current_user).username %></h1>

<div id="conversation-main">
  <div id="conversation-body">
    <%= render @conversation.messages %>
  </div>

  <%= form_with model: @message, local: false do |f| %>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>
    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit %>
  <% end %>
</div>