config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profile', to: 'users#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  post "/payment", to: "payments#create"

  resources :messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  resources :users, only: %i[index]

  resources :posts, except: [:index] do 
    resources :comments, only: [:create]
  end

  resources :fav_posts do 
    collection do
      get :favourite
      get :unfavourite
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord

  validate :picture

  has_many :posts

  has_many :favPost
  has_many :favposts, through: :favPost, source: :post

  has_many :sent_conversations, class_name: 'Conversation', foreign_key: 'sender_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'

  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one :payment
  accepts_nested_attributes_for :payment

  mount_uploader :picture, PictureUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def profile
        render 'users/profile'
    end

end

app/views/users/_user.html.erb
<li>
  <%= user.username %> | <%= link_to 'Message', new_message_path(receiver_id: user) %>
</li>

app/views/users/index.html.erb
<h1>Users</h1>

<ul><%= render @users %></ul>

app/views/users/profile.html.erb
<div class="container mt-4">
    <div class="main-body">

        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin"
                                class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>
                                    <%= current_user.username %>
                                </h4>
                                <p class="text-muted font-size-sm">
                                    user.address 
                                </p>
                                <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary", style: "color: white; text-decoration: none;" %>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-8 mt-5">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Username</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                <%= current_user.username %>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Age</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                user.age
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">E-mail</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                <%= current_user.email %>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                user.address
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>