config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profile', to: 'users#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  post "/payment", to: "payments#create"

  resources :messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  resources :users, only: %i[index]

  resources :posts, except: [:index] do 
    resources :comments, only: [:create]
  end

  resources :fav_posts do 
    collection do
      get :favourite
      get :unfavourite
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord 

    has_many :favPost
    has_many :favusers, through: :favPost, source: :user

    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: { in: 6..30 }
    validates :content, presence: true, length: { minimum: 10 }

    # def is_favourite? current_user
    #     current_user.favposts.include?(self)
    # end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post , only: %i[edit update show destroy]
    before_action :require_permission , only: %i[edit update destroy]
    skip_before_action :authenticate_user!, only: [:index, :show]

    def index
        @posts = Post.all
        respond_to do |format|
            format.json { render json: {plz_work: "OK"} }
            format.html { render 'posts/index' }
        end
    end

    def show
        @comment = Comment.new
        @comments = Post.find(params[:id]).comments.where(parent_id: nil)
    end

    def edit
        @post = Post.new
        render template: "posts/form"
    end

    def update
        if @post.update(post_params)
            flash[:success] = "Post Edited Successfully"
            redirect_to @post
        else
            flash[:danger] = "Enter Valid data"
            render template: "posts/form"
        end
    end

    def new 
        @post = Post.new
        render template: "posts/form"
    end

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            flash[:success] = "Post Created Successfully"
            redirect_to @post
        else
            flash[:danger] = "Enter Valid data"
            render template: "posts/form"
        end
    end

    def destroy
        @post.destroy
        redirect_to root_path
    end


    private

    def post_params
        params.require(:post).permit(:title, :content)
    end

    def set_post
        @post = Post.find(params[:id])
    end

    def require_permission
        if current_user != @post.user
            redirect_to root_path
        end 
    end

end

app/views/posts/_post.html.erb
<article class="col-12 col-md-6 tm-post">
    <%= link_to post_path(post), class: "effect-lily tm-post-link tm-pt-60" do %>
        <div class="tm-post-link-inner">
            <img src="/img/img-01.jpg" alt="Image" class="img-fluid">                            
        </div>
        <h2 class="tm-pt-30 tm-color-primary tm-post-title"><%= post.title %></h2>
    <% end %>            
    <p class="tm-pt-30">
        <%= truncate( post.content, length: 150 ) %>
    </p>
    <div class="d-flex justify-content-between tm-pt-45" height="200">
        <span class="tm-color-primary"><%= post.user.username %></span>
        <span class="tm-color-primary"><%= time_ago_in_words( post.created_at ) %></span>
        <% if user_signed_in? %>
            <% if is_favourite?(post) %>
                <%= link_to "unFavourite", favourite_fav_posts_path(id: post.id), class: "btn btn-info" %>
            <% elsif  %>
                <%= link_to "Favourite", unfavourite_fav_posts_path(id: post.id), class: "btn btn-info" %>
            <% end %>
        <% end %>
    </div>
    <hr>
</article>

app/views/posts/_search.html.erb
<div class="row tm-row">
    <div class="col-12">
        <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
            <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
            <button class="tm-search-button" type="submit">
                <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
            </button>                                
        </form>
    </div>                
</div>  

app/views/posts/form.html.erb
<%= form_with model: @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Your Title Here" %>
  </div>
  <div class="form-group mt-4">
    <%= f.label :content %>
    <%= f.text_area :content, rows: 3, class: "form-control" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary mt-4" %>
<% end %>

app/views/posts/index.html.erb
<div class="row tm-row">
    <%= render @posts %>
</div>

app/views/posts/show.html.erb
<div class="mb-4 text-  center">
    <h2 class="pt-2 tm-color-primary tm-post-title"><%= @post.title %></h2>
    <p class="tm-mb-40">
        posted by <%= @post.user.username %> <br> 
        <%= time_ago_in_words(@post.created_at) %> ago
    </p>
    <%= @post.content %>
    <% if user_signed_in? && current_user == @post.user %>
        <span class="d-block text-right tm-color-primary">
            <%= link_to "Edit", edit_post_path(@post), { style: "text-decoration: none;" ,class: "link-secondary btn btn-info"} %>
            <%= link_to "Delete", post_path(@post), method: :delete, style: "text-decoration: none;" ,class: "link-danger btn btn-warning" %>
        </span>
    <% end %>
</div>
<% if user_signed_in? %>
    <%= render 'comments/form' %>
<% end %>
<% if @comments.any? %>
    <%= render partial: 'comments/comments', locals: {comments: @comments} %>
<% end %>