config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profile', to: 'users#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  post "/payment", to: "payments#create"

  resources :messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  resources :users, only: %i[index]

  resources :posts, except: [:index] do 
    resources :comments, only: [:create]
  end

  resources :fav_posts do 
    collection do
      get :favourite
      get :unfavourite
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/layouts/_cardform.html.erb
<%= form.fields_for :payment do |p| %>
    <li>
    <div class="form-group">
        <%= p.label :card_number, "Card Number", data: { stripe: 'label' } %>
        <%= p.text_field :card_number, class: 'form-control', required: true, data: { stripe: 'card_number' } %>
    </div>

    <div class="form-group">
        <%= p.label :card_cvv, "Card CVV", data: { stripe: 'label' } %>
        <%= p.text_field :card_cvv, class: 'form-control', required: true, data: { stripe: 'card_cvc' } %>
    </div>
    
    <div class="form-group">
        <%= p.label :card_expires, "Card Number", data: { stripe: 'label' } %>
        <%= p.select :card_expires_month, options_for_select(Payment.month_options),
                      { include_blank: 'Month' },
                      "data-stripe" => "exp-Month",
                      class: 'form-control', required: true %>
    </div>

    <div class="form-group">
        <%= p.label :card_number, "Card Number", data: { stripe: 'label' } %>
        <%= p.select :card_expires_year, options_for_select(Payment.year_options),
                      { include_blank: 'Year' },
                      data: { stripe: "exp-year" },
                      class: 'form-control', required: true %>
    </div>

    </li>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row tm-row">
    <hr class="col-12">
    <div class="col-md-6 col-12 tm-color-gray">
        Rails Blog
    </div>
    <div class="col-md-6 col-12 tm-color-gray tm-copyright">
        Abdullah Ahmed
    </div>
</footer>

app/views/layouts/_sidenav.html.erb
<header class="tm-header" id="tm-header">
    <div class="tm-header-wrapper">
        <div class="tm-site-header text-center">
            <%= link_to root_path, style: "text-decoration: none; color: white" do %>
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>            
                <h1 class="text-center">Turtles Blog</h1>
            <% end %>

            <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-lg btn-outline-light my-2 my-lg-0"%>
            <% else %>
                <%= link_to "Signin", user_session_path, class: "btn btn-lg btn-outline-light my-2 my-lg-0"%>
            <% end %>
        </div>
        
        <% if user_signed_in? %>
            <nav class="tm-nav">            
                <ul style="list-style-type: none;" class="text-center">
                    <li class="mb-3">
                        <%= image_tag current_user.picture.url, size: "200x200" if current_user.picture?%>
                    </li> 
                    <li class="mb-3">
                        <%= link_to "Users", users_path, class: "btn btn-lg btn-outline-light my-2 my-lg-0", style: "width: 200px" %>
                    </li> 
                    <li class="mb-3">
                        <%= link_to "Profile", profile_path, class: "btn btn-lg btn-outline-light my-2 my-lg-0", style: "width: 200px"%>
                    </li>
                    <li class="mb-3">
                        <%= link_to "Create Post", new_post_path, class: "btn btn-lg btn-outline-light my-2 my-lg-0", style: "width: 200px"%>
                    </li>
                    <li class="mb-3">
                        <%= link_to "Favourite Post", fav_posts_path, class: "btn btn-lg btn-outline-light my-2 my-lg-0", style: "width: 200px" %>
                    </li>
                </ul>
                
            </nav>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://js.stripe.com/v3/'></script>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'false' %>

  </head>

  <body>

    <%= render "layouts/sidenav" %>
    <div class="container-fluid">
      <%= render "layouts/flash" %>
      <main class="tm-main"> 
        <%= yield %>
      </main>
    </div>
    
    <%= render "layouts/footer" %>
  </body>
</html>